spring:
  application:
    name: r2dbc-postgresql-example

server:
  port: 7878

logging:
  level:
    org.springframework: Trace

datasource:
  host: localhost
  port: 5432
  database: postgres
  username: postgres
  password: Raghuwanshi
